# Generated by Django 3.2.4 on 2022-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(default=None, max_length=8)),
                ('start_time', models.TimeField(default=None)),
                ('end_time', models.TimeField(default=None)),
                ('park_name', models.CharField(default=None, max_length=20)),
                ('park_location', models.CharField(default=None, max_length=20)),
                ('slot_type', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
